#!/bin/bash
secret="${HUB_REPO}-secret"
filepath=${BASEDIR}/deploy/secret-converted.properties
tmp=${BASEDIR}/deploy/tmp-secret.env
cat ${BASEDIR}/cicd/secret-common.env >> ${tmp}
sort -u ${tmp} > ${filepath}
sed 's/\r$//' ${filepath} > ${BASEDIR}/deploy/output-secret.properties

kubectl create secret generic ${secret} --from-env-file=${BASEDIR}/deploy/output-secret.properties -n ${ns}

exit 0

