#!/bin/bash
secret="${HUB_REPO}-secret"
filepath=${BASEDIR}/deploy/secret-converted.properties
tmp=${BASEDIR}/deploy/tmp-secret.env
cat ${BASEDIR}/cicd/secret-common.env >> ${tmp}
sort -u ${tmp} > ${filepath}
sed 's/\r$//' ${filepath} > ${BASEDIR}/deploy/output-secret.properties

output_cm=${BASEDIR}/deploy/output-cm.properties
ns=`cat ${output_cm} | grep namespace= | cut -d "=" -f 2`

kubectl get secret ${secret} -n ${ns} 2> /dev/null
if [ $? -eq 0 ]; then
   kubectl delete secret ${secret} -n ${ns}
fi
kubectl create secret generic ${secret} --from-env-file=${BASEDIR}/deploy/output-secret.properties -n ${ns}

exit 0

